### ISSUE TITLE
feature request: posのshift

### ISSUE THREAD

**Issue by towatti1009** [kous500/CurveBuilding#2]
### 概要
選択中のpos全てまたはその一部を選択してshiftできる機能の要望

### 説明
現在、一度選択したposに対して、shift（上下左右方向へのずらし,worldeditのshiftコマンドに相当する行為）を行う場合、プレイヤー自身でshiftしたい地点へ移動し、`//pos set`コマンドを使用する必要がある。曲線の様子を見ながら調整したい場合や、曲線全体の位置をずらしたい場合、毎回必要な接続点すべてに対して`//pos set`コマンドを使用しなければならず、非常に効率が悪いため、この機能を要望します。

**Comment by kazumasa200** [comment]
@kous500 Issue提供から2ヶ月が過ぎています。対応するか否かを検討してください。

**Comment by kous500** [comment]
今後のアップデートで対応予定です
