### ISSUE TITLE
Question, are you going to update this to newer versions?

### ISSUE THREAD

**Issue by CompbuildREDUX** [kous500/CurveBuilding#21]

**Comment by GreenScreen410** [comment]
I made 1.20.6 support pull request (Bukkit only), Check this file:
[curvebuilding-bukkit-0.7.0.zip](https://github.com/user-attachments/files/16038940/curvebuilding-bukkit-0.7.0.zip)

**Comment by GreenScreen410** [comment]
Fixed: I made new pull request, please use this
https://github.com/kous500/CurveBuilding/pull/24
